### ISSUE TITLE
Add "How we work" to Approach Guide

### ISSUE THREAD

**Issue by jules32** [Openscapes/approach-guide#100]
Capturing How We Work (https://github.com/Openscapes/how_we_work/issues/313) session in the Approach Guide: 

As a record that we did it, and so we can reuse. Include:
- [x] motivation, POP
- [x] Generalized agendas
- [x] email text from Stef

We can maybe start/shape this coworking with @stefaniebutland and @jules32 and then Stef continues

**Comment by stefaniebutland** [comment]
Now in Approach Guide: [How We Work Clinic](https://openscapes.github.io/approach-guide/mentors-framework/how-we-work-clinic.html). @jules32 please close this issue if you're happy with it. I think it includes everything we have / need

**Comment by jules32** [comment]
This looks great, thanks Stef!
