### ISSUE TITLE
Visually distinguish / fade Historical asides

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/approach-guide#27]
Can we make Historical asides look different so they fade back and don't contribute so much to the visual bulk of content?

Quarto [Callouts docs](https://quarto.org/docs/authoring/callouts.html)

Maybe like `::: {.callout-note collapse="true"}` so they're expandable,  and all named "Historical aside". 

I'm going to implement this in one section so we can evaluate

**Comment by stefaniebutland** [comment]
ooooh I love them.

**Comment by jules32** [comment]
Yes absolutely!

**Comment by stefaniebutland** [comment]
added in https://github.com/Openscapes/approach-guide/pull/28
