### ISSUE TITLE
cohort repo edit suggested before access is given

### ISSUE THREAD

**Issue by cclatterbuck** [Openscapes/approach-guide#42]
https://github.com/Openscapes/approach-guide/blob/effd419c32b387338d2b6279fc34cde7955e9039/champions/pre-cohort-engage.qmd#L336

The week prior email suggests that cohort members have edit access to the cohort repo, but the approach guide suggests using Kyber to create the GitHub team just prior to the GitHub Clinic (currently Call 2). Do cohort members have repo access prior to this time, and if so, how? 

Relatedly, does Kyber add the GitHub usernames to the Openscapes organization and the cohort team? Or, do cohort members need to be added to the Openscapes organization prior to using the Kyber process which puts them in a team?

**Comment by jules32** [comment]
Hi! I will update this email text - cohort members do not need to know about github prior to Call 2!

Kyber will add GitHub usernames to the Openscapes org - unless you provide a different org - and to the cohort team you provide!

**Comment by jules32** [comment]
Updated with this commit: https://github.com/Openscapes/approach-guide/commit/c990e4c20a5dd44cfa1064e3909924d1e0f037b5
