### ISSUE TITLE
create Cohort Timeline graphic

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/approach-guide#82]
make a version of SWRCB's that Anna Holder shared. See [High level timeline](https://openscapes.github.io/approach-guide/champions/design.html#high-level-timeline) graphic in Approach Guide
she made in visio; use draw.io since visio is licensed.

I wonder if visio can export to format that draw.io can use. Search of draw.io site docs did not indicate a clear path. DM'd Corey to see if she knows

**Comment by stefaniebutland** [comment]
Sweet! Thank you @cclatterbuck! I've imported your SWRCB Cohort timeline into draw.io in the Openscapes org! Ready to adapt soon. 

How to (rough notes from memory). Some of these are out of order:
- Goal: import `Openscapes_SWAMPCohort_Timeline.vsdx` Visio file into draw.io
- go to draw.io via browser
- selected GitHub as storage location for files
- authorize GitHub repo; I chose `https://github.com/Openscapes/approach-guide` 
- Create > blank opens a familiar looking interface, then File > Import > from device (or wherever the file is you want to import
  - I think this is when I was prompted to authorize the app to create a file in GitHub
- I was prompted to install draw.io for GitHub and chose to grant permission to all repos in Openscapes org
  - after that, clicked Try again to create file
- success! Ready to edit for any Openscapes Cohort starting with Fred Hutch

![Screenshot 2023-09-05 at 9 47 39 AM](https://github.com/Openscapes/approach-guide/assets/11927811/37d7df67-9499-433f-be61-0391c16392dc)

**Comment by stefaniebutland** [comment]
Corey's original SWAMP Cohort timeline currently saved at https://github.com/Openscapes/approach-guide/blob/main/approach/images/cohort-timeline.drawio

**WIP**

To adapt for Fred Hutch, here's what I did.
- open draw.io in browser. Because I set it to use GitHub as storage location, it shows: 

![Screenshot 2023-09-07 at 1 53 12 PM](https://github.com/Openscapes/approach-guide/assets/11927811/e79012fe-63d0-4cb5-9ad6-b7e29d8e4384)

- Open existing file. Scroll down to Openscapes/approach-guide repo and the .drawio file in main > approach > images

![Screenshot 2023-09-07 at 1 54 22 PM](https://github.com/Openscapes/approach-guide/assets/11927811/03ecb7c9-e58c-43c7-8bdb-cfc3d8c35599)

- once open, we can see tabs at bottom for different cohort timelines. I noticed when you go to a tab, it may look blank. Scroll to bring content into view. Adding new timelines to new tabs seems like a good strategy since this is the source draw.io file and we'll export image files to use in different locations.

![Screenshot 2023-09-07 at 1 58 10 PM](https://github.com/Openscapes/approach-guide/assets/11927811/877e8a93-f077-4da0-81d5-a489951f85ed)

- To adapt a timeline, right click a tab > duplicate > name. It's cool that a red box shows up to tell you to save and when you save you're prompted for a Git commit message!

![Screenshot 2023-09-07 at 2 04 41 PM](https://github.com/Openscapes/approach-guide/assets/11927811/35b76707-b5d8-4240-b173-5e2166a532b1)

**Comment by stefaniebutland** [comment]
@jules32 please check slide 4 for the next iteration.
I'll add to Approach Guide (replace [current fig](https://openscapes.github.io/approach-guide/champions/design.html#high-level-timeline)) once agreed on.

**Comment by jules32** [comment]
Looks good @stefaniebutland ! I made some final font increases and it's good to go! Thanks
