### ISSUE TITLE
Add NMFS example elevator pitches

### ISSUE THREAD

**Issue by stefaniebutland** [Openscapes/approach-guide#9]
Add to https://openscapes.github.io/approach-guide/champions/cohort-planning.html I think.

"there’s a lot of coord that goes on with the partner groups as they get their ducks in a row."

add section “Examples”
e.g. " Here’s example of a few texts that worked for Eric Ward at NWFSC and Megsie Siple at AFSC"

**Comment by stefaniebutland** [comment]
Julie & Eli added these to NMFS Openscapes README and we're hoping to put that in NMFS Wiki and link to Wiki from Approach Guide

**Comment by stefaniebutland** [comment]
@jules32 Is this issue still relevant here? Or should I close it?

**Comment by jules32** [comment]
Yes let's close here, thanks!
